# .github/workflows/release.yml
name: Build and Release bbctl

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Build binary
        id: build
        run: |
          BIN=bbctl-${{ matrix.goos }}-${{ matrix.goarch }}
          [[ "${{ matrix.goos }}" == "windows" ]] && BIN=${BIN}.exe
          echo "BIN=$BIN" >> "$GITHUB_ENV"
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -ldflags="-s -w" -o "$BIN"
          ls -l "$BIN"

      - name: Package artifact
        env:
          BIN: ${{ env.BIN }}
        run: |
          echo "Packaging: $BIN"
          ls -l "$BIN" || exit 1
          mkdir -p release
          tar -czf release/${BIN}.tar.gz "$BIN"
          ls -l release/
