name: Build and Release bbctl

on:
  push:
    tags:
      - 'v*'
  pull_request:

permissions:
  contents: write

jobs:
  build:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    name: Build, Package & Publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Build binary
        run: |
          BIN_NAME=bbctl
          [[ "${{ matrix.goos }}" == "windows" ]] && BIN_NAME=${BIN_NAME}.exe
          echo "BIN_NAME=$BIN_NAME" >> "$GITHUB_ENV"
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build \
            -ldflags="-s -w -X 'github.com/vinisman/bbctl/cmd.Version=${GITHUB_REF_NAME}' -X 'github.com/vinisman/bbctl/cmd.Commit=${GITHUB_SHA}'" \
            -o $BIN_NAME

      - name: Package artifact
        run: |
          mkdir -p release
          ARTIFACT_NAME=bbctl-${GITHUB_REF_NAME}-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
          tar -czf release/${ARTIFACT_NAME} "$BIN_NAME"
          echo "ARTIFACT_NAME=${ARTIFACT_NAME}" >> "$GITHUB_ENV"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.goos }}-${{ matrix.goarch }}
          path: release/*.tar.gz
          retention-days: 1

  create-release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts

      - name: List downloaded artifacts
        run: |
          find release-artifacts -name "*.tar.gz" | xargs ls -la

      - name: Prepare release assets
        run: |
          # Собираем все артефакты в одну папку
          mkdir -p release-final
          find release-artifacts -name "*.tar.gz" -exec cp {} release-final/ \;
          ls -la release-final/

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if gh release view "${GITHUB_REF_NAME}" >/dev/null 2>&1; then
            echo "Release ${GITHUB_REF_NAME} already exists"
            exit 0
          fi

          PREV_TAG=$(git tag --sort=-creatordate | sed -n '2p' 2>/dev/null || echo "")
          
          if [ -z "$PREV_TAG" ]; then
            NOTES="## First release\n\n"
            # Get commits from feature/bugfix branches and extract their messages
            COMMITS=$(git log --oneline --format='%s|%h' --grep='\(feature/\|bugfix/\)' | while IFS='|' read -r message hash; do
              echo "- $message ($hash)"
            done || echo "")
          else
            NOTES="## Changes since $PREV_TAG\n\n"
            # Get commits since last tag from feature/bugfix branches
            COMMITS=$(git log $PREV_TAG..HEAD --oneline --format='%s|%h' --grep='\(feature/\|bugfix/\)' | while IFS='|' read -r message hash; do
              echo "- $message ($hash)"
            done || echo "")
          fi
          
          if [ -z "$COMMITS" ]; then
            NOTES+="No feature or bugfix commits in this release"
          else
            NOTES+="$COMMITS"
          fi
          
          echo -e "$NOTES" > release_notes.md
          cat release_notes.md
          
          gh release create "${GITHUB_REF_NAME}" release-final/*.tar.gz \
            --title "${GITHUB_REF_NAME}" \
            --notes-file release_notes.md

  build-check:
    name: Build Check on PR
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Build binary
        run: |
          BIN_NAME=bbctl-pr-${{ github.sha }}-${{ matrix.goos }}-${{ matrix.goarch }}
          [[ "${{ matrix.goos }}" == "windows" ]] && BIN_NAME=${BIN_NAME}.exe
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build \
            -ldflags="-s -w -X 'github.com/vinisman/bbctl/cmd.Version=pr-${{ github.sha }}' -X 'github.com/vinisman/bbctl/cmd.Commit=${GITHUB_SHA}'" \
            -o $BIN_NAME