# .github/workflows/release.yml
name: Build and Release bbctl

on:
  push:
    tags:
      - 'v*'
  pull_request:

permissions:
  contents: write

jobs:
  build:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    name: Build, Package & Publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Build binary
        id: build
        run: |
          BIN=bbctl-${GITHUB_REF_NAME}-${{ matrix.goos }}-${{ matrix.goarch }}
          [[ "${{ matrix.goos }}" == "windows" ]] && BIN=${BIN}.exe
          echo "BIN=$BIN" >> "$GITHUB_ENV"
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -ldflags="-s -w -X 'github.com/vinisman/bbctl/cmd.Version=${GITHUB_REF_NAME}' -X 'github.com/vinisman/bbctl/cmd.Commit=${GITHUB_SHA}'" -o $BIN
          ls -l $BIN

      - name: Package artifact
        env:
          BIN: ${{ env.BIN }}
        run: |
          mkdir -p release
          tar -czf release/${BIN}.tar.gz "$BIN"
          ls -l release

      - name: Create GitHub Release and upload assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch --prune --unshallow --tags || true
          
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^1 2>/dev/null || echo "")
          if [ -z "$PREV_TAG" ]; then
            # First release or no previous tag, include all commits
            git log --branches='feature/*' --branches='bugfix/*' --pretty=format:'- %s (%an)' > release_notes.md
          else
            git log $PREV_TAG..HEAD --branches='feature/*' --branches='bugfix/*' --pretty=format:'- %s (%an)' > release_notes.md
          fi
          
          gh release create "${GITHUB_REF_NAME}" release/*.tar.gz \
            --notes-file release_notes.md \
            --repo "${GITHUB_REPOSITORY}"
  build-check:
    name: Build Check on PR
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Build binary
        run: |
          BIN=bbctl-${GITHUB_REF_NAME}-${{ matrix.goos }}-${{ matrix.goarch }}
          [[ "${{ matrix.goos }}" == "windows" ]] && BIN=${BIN}.exe
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -ldflags="-s -w -X 'github.com/vinisman/bbctl/cmd.Version=${GITHUB_REF_NAME}' -X 'github.com/vinisman/bbctl/cmd.Commit=${GITHUB_SHA}'" -o $BIN
          ls -l $BIN